name: pycapture2_firefly
channels:
  - defaults
dependencies:
  - certifi=2021.5.30=py36haa95532_0
  - pip=21.2.2=py36haa95532_0
  - python=3.6.13=h3758d61_0
  - setuptools=58.0.4=py36haa95532_0
  - sqlite=3.51.1=hda9a48d_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py36h7fe50ca_0
  - pip:
      - numpy==1.19.5
      - pycapture2==2.13.61
prefix: C:\Users\bapodaca\anaconda3\envs\pycapture2_firefly
